{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='tinkerbellMachineTemplate', url='', help='"TinkerbellMachineTemplate is the Schema for the tinkerbellmachinetemplates API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of TinkerbellMachineTemplate', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'infrastructure.cluster.x-k8s.io/v1beta1',
    kind: 'TinkerbellMachineTemplate',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"TinkerbellMachineTemplateSpec defines the desired state of TinkerbellMachineTemplate."'),
  spec: {
    '#template':: d.obj(help='"TinkerbellMachineTemplateResource describes the data needed to create am TinkerbellMachine from a template."'),
    template: {
      '#spec':: d.obj(help='"Spec is the specification of the desired behavior of the machine."'),
      spec: {
        '#bootOptions':: d.obj(help='"BootOptions are options that control the booting of Hardware."'),
        bootOptions: {
          '#custombootConfig':: d.obj(help='"CustombootConfig is the configuration for the \\"customboot\\" boot mode.\\nThis allows users to define custom BMC Actions."'),
          custombootConfig: {
            '#postActions':: d.obj(help='"PostActions are the BMC Actions that will be run after all Workflow Actions have completed.\\nIn most cases these Actions should get a Machine into a state where it can be powered off or rebooted and remove any mounted virtual media.\\nThese Actions will be run only if the main Workflow Actions complete successfully."'),
            postActions: {
              '#bootDevice':: d.obj(help='"BootDevice is the device to set as the first boot device on the Machine."'),
              bootDevice: {
                '#withDevice':: d.fn(help='"Device is the name of the device to set as the first boot device."', args=[d.arg(name='device', type=d.T.string)]),
                withDevice(device): { bootDevice+: { device: device } },
                '#withEfiBoot':: d.fn(help='"EFIBoot indicates whether the boot device should be set to efiboot mode."', args=[d.arg(name='efiBoot', type=d.T.boolean)]),
                withEfiBoot(efiBoot): { bootDevice+: { efiBoot: efiBoot } },
                '#withPersistent':: d.fn(help='"Persistent indicates whether the boot device should be set persistently as the first boot device."', args=[d.arg(name='persistent', type=d.T.boolean)]),
                withPersistent(persistent): { bootDevice+: { persistent: persistent } },
              },
              '#oneTimeBootDeviceAction':: d.obj(help='"OneTimeBootDeviceAction represents a baseboard management one time set boot device operation."'),
              oneTimeBootDeviceAction: {
                '#withDevice':: d.fn(help='"Devices represents the boot devices, in order for setting one time boot.\\nCurrently only the first device in the slice is used to set one time boot."', args=[d.arg(name='device', type=d.T.array)]),
                withDevice(device): { oneTimeBootDeviceAction+: { device: if std.isArray(v=device) then device else [device] } },
                '#withDeviceMixin':: d.fn(help='"Devices represents the boot devices, in order for setting one time boot.\\nCurrently only the first device in the slice is used to set one time boot."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='device', type=d.T.array)]),
                withDeviceMixin(device): { oneTimeBootDeviceAction+: { device+: if std.isArray(v=device) then device else [device] } },
                '#withEfiBoot':: d.fn(help='"EFIBoot instructs the machine to use EFI boot."', args=[d.arg(name='efiBoot', type=d.T.boolean)]),
                withEfiBoot(efiBoot): { oneTimeBootDeviceAction+: { efiBoot: efiBoot } },
              },
              '#virtualMediaAction':: d.obj(help='"VirtualMediaAction represents a baseboard management virtual media insert/eject."'),
              virtualMediaAction: {
                '#withKind':: d.fn(help='"Kind represents the kind of virtual media."', args=[d.arg(name='kind', type=d.T.string)]),
                withKind(kind): { virtualMediaAction+: { kind: kind } },
                '#withMediaURL':: d.fn(help='"mediaURL represents the URL of the image to be inserted into the virtual media, or empty to eject media."', args=[d.arg(name='mediaURL', type=d.T.string)]),
                withMediaURL(mediaURL): { virtualMediaAction+: { mediaURL: mediaURL } },
              },
              '#withPowerAction':: d.fn(help='"PowerAction represents a baseboard management power operation."', args=[d.arg(name='powerAction', type=d.T.string)]),
              withPowerAction(powerAction): { powerAction: powerAction },
            },
            '#preparingActions':: d.obj(help='"PreparingActions are the BMC Actions that will be run before any Workflow Actions.\\nIn most cases these Actions should get a Machine into a state where a Tink Agent is running."'),
            preparingActions: {
              '#bootDevice':: d.obj(help='"BootDevice is the device to set as the first boot device on the Machine."'),
              bootDevice: {
                '#withDevice':: d.fn(help='"Device is the name of the device to set as the first boot device."', args=[d.arg(name='device', type=d.T.string)]),
                withDevice(device): { bootDevice+: { device: device } },
                '#withEfiBoot':: d.fn(help='"EFIBoot indicates whether the boot device should be set to efiboot mode."', args=[d.arg(name='efiBoot', type=d.T.boolean)]),
                withEfiBoot(efiBoot): { bootDevice+: { efiBoot: efiBoot } },
                '#withPersistent':: d.fn(help='"Persistent indicates whether the boot device should be set persistently as the first boot device."', args=[d.arg(name='persistent', type=d.T.boolean)]),
                withPersistent(persistent): { bootDevice+: { persistent: persistent } },
              },
              '#oneTimeBootDeviceAction':: d.obj(help='"OneTimeBootDeviceAction represents a baseboard management one time set boot device operation."'),
              oneTimeBootDeviceAction: {
                '#withDevice':: d.fn(help='"Devices represents the boot devices, in order for setting one time boot.\\nCurrently only the first device in the slice is used to set one time boot."', args=[d.arg(name='device', type=d.T.array)]),
                withDevice(device): { oneTimeBootDeviceAction+: { device: if std.isArray(v=device) then device else [device] } },
                '#withDeviceMixin':: d.fn(help='"Devices represents the boot devices, in order for setting one time boot.\\nCurrently only the first device in the slice is used to set one time boot."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='device', type=d.T.array)]),
                withDeviceMixin(device): { oneTimeBootDeviceAction+: { device+: if std.isArray(v=device) then device else [device] } },
                '#withEfiBoot':: d.fn(help='"EFIBoot instructs the machine to use EFI boot."', args=[d.arg(name='efiBoot', type=d.T.boolean)]),
                withEfiBoot(efiBoot): { oneTimeBootDeviceAction+: { efiBoot: efiBoot } },
              },
              '#virtualMediaAction':: d.obj(help='"VirtualMediaAction represents a baseboard management virtual media insert/eject."'),
              virtualMediaAction: {
                '#withKind':: d.fn(help='"Kind represents the kind of virtual media."', args=[d.arg(name='kind', type=d.T.string)]),
                withKind(kind): { virtualMediaAction+: { kind: kind } },
                '#withMediaURL':: d.fn(help='"mediaURL represents the URL of the image to be inserted into the virtual media, or empty to eject media."', args=[d.arg(name='mediaURL', type=d.T.string)]),
                withMediaURL(mediaURL): { virtualMediaAction+: { mediaURL: mediaURL } },
              },
              '#withPowerAction':: d.fn(help='"PowerAction represents a baseboard management power operation."', args=[d.arg(name='powerAction', type=d.T.string)]),
              withPowerAction(powerAction): { powerAction: powerAction },
            },
            '#withPostActions':: d.fn(help='"PostActions are the BMC Actions that will be run after all Workflow Actions have completed.\\nIn most cases these Actions should get a Machine into a state where it can be powered off or rebooted and remove any mounted virtual media.\\nThese Actions will be run only if the main Workflow Actions complete successfully."', args=[d.arg(name='postActions', type=d.T.array)]),
            withPostActions(postActions): { spec+: { template+: { spec+: { bootOptions+: { custombootConfig+: { postActions: if std.isArray(v=postActions) then postActions else [postActions] } } } } } },
            '#withPostActionsMixin':: d.fn(help='"PostActions are the BMC Actions that will be run after all Workflow Actions have completed.\\nIn most cases these Actions should get a Machine into a state where it can be powered off or rebooted and remove any mounted virtual media.\\nThese Actions will be run only if the main Workflow Actions complete successfully."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='postActions', type=d.T.array)]),
            withPostActionsMixin(postActions): { spec+: { template+: { spec+: { bootOptions+: { custombootConfig+: { postActions+: if std.isArray(v=postActions) then postActions else [postActions] } } } } } },
            '#withPreparingActions':: d.fn(help='"PreparingActions are the BMC Actions that will be run before any Workflow Actions.\\nIn most cases these Actions should get a Machine into a state where a Tink Agent is running."', args=[d.arg(name='preparingActions', type=d.T.array)]),
            withPreparingActions(preparingActions): { spec+: { template+: { spec+: { bootOptions+: { custombootConfig+: { preparingActions: if std.isArray(v=preparingActions) then preparingActions else [preparingActions] } } } } } },
            '#withPreparingActionsMixin':: d.fn(help='"PreparingActions are the BMC Actions that will be run before any Workflow Actions.\\nIn most cases these Actions should get a Machine into a state where a Tink Agent is running."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='preparingActions', type=d.T.array)]),
            withPreparingActionsMixin(preparingActions): { spec+: { template+: { spec+: { bootOptions+: { custombootConfig+: { preparingActions+: if std.isArray(v=preparingActions) then preparingActions else [preparingActions] } } } } } },
          },
          '#withBootMode':: d.fn(help='"BootMode is the type of booting that will be done. One of \\"netboot\\", \\"isoboot\\", or \\"customboot\\"."', args=[d.arg(name='bootMode', type=d.T.string)]),
          withBootMode(bootMode): { spec+: { template+: { spec+: { bootOptions+: { bootMode: bootMode } } } } },
          '#withIsoURL':: d.fn(help='"ISOURL is the URL of the ISO that will be one-time booted.\\nA HardwareRef that contains a spec.BmcRef must be provided.\\n\\nThe format of the ISOURL must be http://$IP:$Port/iso/hook.iso\\nThe name of the ISO file must have the .iso extension, but the name can be anything.\\nThe $IP and $Port should generally point to the IP and Port of the Smee server\\nas this is where the ISO patching endpoint lives.\\nThe controller will append the MAC address of the hardware in the ISO URL\\nright before the iso file name in the URL.\\nMAC address is then used to retrieve hardware specific information such as\\nIPAM info, custom kernel cmd line args and populate the worker ID for the tink worker/agent.\\nFor ex. the above format would be replaced to http://$IP:$Port/iso/<macAddress>/hook.iso\\n\\nBootMode must be set to \\"isoboot\\"."', args=[d.arg(name='isoURL', type=d.T.string)]),
          withIsoURL(isoURL): { spec+: { template+: { spec+: { bootOptions+: { isoURL: isoURL } } } } },
        },
        '#hardwareAffinity':: d.obj(help='"HardwareAffinity allows filtering for hardware."'),
        hardwareAffinity: {
          '#preferred':: d.obj(help='"Preferred are the preferred hardware affinity terms. Hardware matching these terms are preferred according to the\\nweights provided, but are not required."'),
          preferred: {
            '#hardwareAffinityTerm':: d.obj(help='"HardwareAffinityTerm is the term associated with the corresponding weight."'),
            hardwareAffinityTerm: {
              '#labelSelector':: d.obj(help='"LabelSelector is used to select for particular hardware by label."'),
              labelSelector: {
                '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
                matchExpressions: {
                  '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
                  withKey(key): { key: key },
                  '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
                  withOperator(operator): { operator: operator },
                  '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
                  withValues(values): { values: if std.isArray(v=values) then values else [values] },
                  '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
                  withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
                },
                '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
                withMatchExpressions(matchExpressions): { hardwareAffinityTerm+: { labelSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
                '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
                withMatchExpressionsMixin(matchExpressions): { hardwareAffinityTerm+: { labelSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
                '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
                withMatchLabels(matchLabels): { hardwareAffinityTerm+: { labelSelector+: { matchLabels: matchLabels } } },
                '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
                withMatchLabelsMixin(matchLabels): { hardwareAffinityTerm+: { labelSelector+: { matchLabels+: matchLabels } } },
              },
            },
            '#withWeight':: d.fn(help='"Weight associated with matching the corresponding hardwareAffinityTerm, in the range 1-100."', args=[d.arg(name='weight', type=d.T.integer)]),
            withWeight(weight): { weight: weight },
          },
          '#required':: d.obj(help="\"Required are the required hardware affinity terms.  The terms are OR'd together, hardware must match one term to\\nbe considered.\""),
          required: {
            '#labelSelector':: d.obj(help='"LabelSelector is used to select for particular hardware by label."'),
            labelSelector: {
              '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
              matchExpressions: {
                '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
                withKey(key): { key: key },
                '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values.\\nValid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
                withOperator(operator): { operator: operator },
                '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."', args=[d.arg(name='values', type=d.T.array)]),
                withValues(values): { values: if std.isArray(v=values) then values else [values] },
                '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn,\\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\\nthe values array must be empty. This array is replaced during a strategic\\nmerge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
                withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
              },
              '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
              withMatchExpressions(matchExpressions): { labelSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } },
              '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
              withMatchExpressionsMixin(matchExpressions): { labelSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } },
              '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabels(matchLabels): { labelSelector+: { matchLabels: matchLabels } },
              '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\\nmap is equivalent to an element of matchExpressions, whose key field is \\"key\\", the\\noperator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabelsMixin(matchLabels): { labelSelector+: { matchLabels+: matchLabels } },
            },
          },
          '#withPreferred':: d.fn(help='"Preferred are the preferred hardware affinity terms. Hardware matching these terms are preferred according to the\\nweights provided, but are not required."', args=[d.arg(name='preferred', type=d.T.array)]),
          withPreferred(preferred): { spec+: { template+: { spec+: { hardwareAffinity+: { preferred: if std.isArray(v=preferred) then preferred else [preferred] } } } } },
          '#withPreferredMixin':: d.fn(help='"Preferred are the preferred hardware affinity terms. Hardware matching these terms are preferred according to the\\nweights provided, but are not required."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='preferred', type=d.T.array)]),
          withPreferredMixin(preferred): { spec+: { template+: { spec+: { hardwareAffinity+: { preferred+: if std.isArray(v=preferred) then preferred else [preferred] } } } } },
          '#withRequired':: d.fn(help="\"Required are the required hardware affinity terms.  The terms are OR'd together, hardware must match one term to\\nbe considered.\"", args=[d.arg(name='required', type=d.T.array)]),
          withRequired(required): { spec+: { template+: { spec+: { hardwareAffinity+: { required: if std.isArray(v=required) then required else [required] } } } } },
          '#withRequiredMixin':: d.fn(help="\"Required are the required hardware affinity terms.  The terms are OR'd together, hardware must match one term to\\nbe considered.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='required', type=d.T.array)]),
          withRequiredMixin(required): { spec+: { template+: { spec+: { hardwareAffinity+: { required+: if std.isArray(v=required) then required else [required] } } } } },
        },
        '#withHardwareName':: d.fn(help='"Those fields are set programmatically, but they cannot be re-constructed from \\"state of the world\\", so\\nwe put them in spec instead of status."', args=[d.arg(name='hardwareName', type=d.T.string)]),
        withHardwareName(hardwareName): { spec+: { template+: { spec+: { hardwareName: hardwareName } } } },
        '#withImageLookupBaseRegistry':: d.fn(help='"ImageLookupBaseRegistry is the base Registry URL that is used for pulling images,\\nif not set, the default will be to use ghcr.io/tinkerbell/cluster-api-provider-tinkerbell."', args=[d.arg(name='imageLookupBaseRegistry', type=d.T.string)]),
        withImageLookupBaseRegistry(imageLookupBaseRegistry): { spec+: { template+: { spec+: { imageLookupBaseRegistry: imageLookupBaseRegistry } } } },
        '#withImageLookupFormat':: d.fn(help='"ImageLookupFormat is the URL naming format to use for machine images when\\na machine does not specify. When set, this will be used for all cluster machines\\nunless a machine specifies a different ImageLookupFormat. Supports substitutions\\nfor {{.BaseRegistry}}, {{.OSDistro}}, {{.OSVersion}} and {{.KubernetesVersion}} with\\nthe basse URL, OS distribution, OS version, and kubernetes version, respectively.\\nBaseRegistry will be the value in ImageLookupBaseRegistry or ghcr.io/tinkerbell/cluster-api-provider-tinkerbell\\n(the default), OSDistro will be the value in ImageLookupOSDistro or ubuntu (the default),\\nOSVersion will be the value in ImageLookupOSVersion or default based on the OSDistro\\n(if known), and the kubernetes version as defined by the packages produced by\\nkubernetes/release: v1.13.0, v1.12.5-mybuild.1, or v1.17.3. For example, the default\\nimage format of {{.BaseRegistry}}/{{.OSDistro}}-{{.OSVersion}}:{{.KubernetesVersion}}.gz will\\nattempt to pull the image from that location. See also: https://golang.org/pkg/text/template/"', args=[d.arg(name='imageLookupFormat', type=d.T.string)]),
        withImageLookupFormat(imageLookupFormat): { spec+: { template+: { spec+: { imageLookupFormat: imageLookupFormat } } } },
        '#withImageLookupOSDistro':: d.fn(help='"ImageLookupOSDistro is the name of the OS distro to use when fetching machine images,\\nif not set it will default to ubuntu."', args=[d.arg(name='imageLookupOSDistro', type=d.T.string)]),
        withImageLookupOSDistro(imageLookupOSDistro): { spec+: { template+: { spec+: { imageLookupOSDistro: imageLookupOSDistro } } } },
        '#withImageLookupOSVersion':: d.fn(help='"ImageLookupOSVersion is the version of the OS distribution to use when fetching machine\\nimages. If not set it will default based on ImageLookupOSDistro."', args=[d.arg(name='imageLookupOSVersion', type=d.T.string)]),
        withImageLookupOSVersion(imageLookupOSVersion): { spec+: { template+: { spec+: { imageLookupOSVersion: imageLookupOSVersion } } } },
        '#withProviderID':: d.fn(help='', args=[d.arg(name='providerID', type=d.T.string)]),
        withProviderID(providerID): { spec+: { template+: { spec+: { providerID: providerID } } } },
        '#withTemplateOverride':: d.fn(help='"TemplateOverride overrides the default Tinkerbell template used by CAPT.\\nYou can learn more about Tinkerbell templates here: https://tinkerbell.org/docs/concepts/templates/"', args=[d.arg(name='templateOverride', type=d.T.string)]),
        withTemplateOverride(templateOverride): { spec+: { template+: { spec+: { templateOverride: templateOverride } } } },
      },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
